import rawCommonApp from "@/data/commonapp.json";

/**
 * Facts from Common App's public first-year requirements grid, generated by
 * scripts/import-commonapp-grid.py. Only what the grid positively states is
 * here: a blank cell in the grid means "not stated", not "no", so absent
 * fields must never be shown as a negative.
 */
export interface CommonAppFacts {
  gridName: string;
  /** ED, EDII, EA, EAII, REA, RD as ISO dates, or "Rolling". */
  deadlines: Partial<Record<"ED" | "EDII" | "EA" | "EAII" | "REA" | "RD", string>>;
  feeUS?: string;
  feeIntl?: string;
  /** "Accepted", "U.S. only" or "Not Accepted". */
  feeWaiver?: string;
  personalEssayRequired?: true;
  coursesGradesRequired?: true;
  /** Where portfolios are collected, when the school collects them. */
  portfolio?: string;
  teacherEvaluations?: number;
  otherEvaluations?: number;
  counselorRecommendation?: true;
  midYearReport?: true;
}

interface CommonAppFile {
  source: { name: string; url: string; updated: string };
  byCollege: Record<string, CommonAppFacts>;
}

const commonApp = rawCommonApp as unknown as CommonAppFile;

export const COMMON_APP_SOURCE = commonApp.source;

export function getCommonAppFacts(collegeId: string): CommonAppFacts | null {
  return commonApp.byCollege[collegeId] ?? null;
}
