import rawPrograms from "@/data/programs.json";

/**
 * Real degree counts per school and field, generated by
 * scripts/import-programs.mjs from the IPEDS Completions survey. Keyed by
 * college id, so a school added to colleges.json gets an entry the next time
 * that script runs — nothing here needs to change.
 */
interface ProgramsFile {
  source: string;
  year: string;
  byCollege: Record<string, Record<string, number>>;
}

const programs = rawPrograms as unknown as ProgramsFile;

/** Fewer degrees a year than this isn't treated as a real program (one music degree a year is not a music program). */
export const MIN_PROGRAM_DEGREES = 10;

export const PROGRAMS_SOURCE = { source: programs.source, year: programs.year };

/** Bachelor's degrees the school awarded in a field (0 if none reported). */
export function degreesIn(collegeId: string, field: string): number {
  return programs.byCollege[collegeId]?.[field] ?? 0;
}

/** True when the school awards a meaningful number of degrees in any of the given fields. */
export function offersProgram(collegeId: string, fields: string[]): boolean {
  return fields.some((f) => degreesIn(collegeId, f) >= MIN_PROGRAM_DEGREES);
}
